CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS concursos (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  dou_url TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS materias (
  id SERIAL PRIMARY KEY,
  contest_id INT NOT NULL REFERENCES concursos(id) ON DELETE CASCADE,
  nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS conteudos (
  id SERIAL PRIMARY KEY,
  materia_id INT NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  embedding VECTOR(1536)
);

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  data JSONB,
  result JSONB,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
